### ISSUE TITLE
Creare Indice Piano di Qualifica

### ISSUE THREAD

**Issue by AndreaBreggion** [CodeOfDutyJS/documentazione#15]

**Comment by strang3nt** [comment]
Introduzione
In cui, dopo una doverosa premessa sono indicati: lo scopo del documento, lo 
scopo del progetto, indicazioni riguardanti il glossario e i riferimenti  utilizzati durante 
la stesura del documento.

Qualità di processo
Sono presenti i processi e le attività per cui sono state individuate 
metriche, nonchè il valore oltre il quale la metrica è considerata 
soddisfatta.

Qualità di prodotto
In cui sono presenti due sezioni, dedicate a qualità dell'architettura e 
qualità del software. Per ogni sezione sono indicate metriche e valori che le 
soddisfano. In particolare per quanto riguarda la qualità del software il 
team ha deciso di fare affidamento allo standard ISO 9126.
  
Appendice
Quest'ultima sezione è divisa in più sottosezioni, e ne saranno aggiunte
ulteriori con l'evolversi dell'attività di progetto. Attualmente sono mostrati i risultati delle misurazioni, 
gli standard utilizzati ed infine sono mostrate alcune riflessioni 
che riguardano il miglioramento continuo.
