### ISSUE TITLE
Creare Indice Analisi dei Requisiti

### ISSUE THREAD

**Issue by AndreaBreggion** [CodeOfDutyJS/documentazione#17]

**Comment by masca9993** [comment]
[Analisi dei Requisiti.zip](https://github.com/CodeOfDutyJS/documentazione/files/5685085/Analisi.dei.Requisiti.zip)

**Comment by Damix48** [comment]
### Prima possibile struttura

1. **Introduzione**
1.1 _Scopo del Documento_
1.2 _Scopo del Prodotti_
1.3 _Riferimenti_
1.4 _Overview_
2. **Descrizione Generale**
2.1 _Funzionalità del Prodotto_
2.2 _Attori_
2.3 _Vincoli_
2.4 _Assunzioni e Dipendenze_
3. **Casi d’uso**
3.1 _UC1_
3.n  _UCn_
4. **Requisiti**
4.1 _Funzionali_
4.2 _Performance_
4.3 _Gestione Dati_
  4.4 _Qualità_
    - 4.4.1 Affidabilità
    - 4.4.2 Accessibilità
    - 4.4.3 Sicurezza
    - 4.4.4 Manutebilità
    - 4.4.5 Portabilità

Nel branch `analisi-dei-requisiti`:
https://github.com/CodeOfDutyJS/documentazione/blob/edb0c63978c35c48cdf28d41ecd5307ef1435c55/analisi-dei-requisiti/main.tex#L30-L33
Struttura da @masca9993

**Comment by Damix48** [comment]
### Seconda possibile struttura

Questa struttura è molto più simile allo standard [IEEE 830-1998](https://standards.ieee.org/standard/830-1998.html) anche se stato rimpiazzato con [IEEE/ISO/IEC 29148-2011](https://standards.ieee.org/standard/29148-2011.html).

1. **Introduzione**
1.1 _Scopo del Documento_
1.2 _Scopo del Prodotti_
1.3 _Riferimenti_
1.4 _Overview_
2. **Descrizione Generale**
2.1 _Funzionalità del Prodotto_
2.2 _Attori_
2.3 _Vincoli_
2.4 _Assunzioni e Dipendenze_
3. **Requisiti specifici**
  3.1 _Casi d'uso_
    - 3.1.1 UC1
      - 3.1.1.1 UC1.1
      - 3.1.1.n UC1.n
      - 3.1.1.n+1 Requisiti Associati
    - 3.1.n UCn
      - 3.1.n.1 UCn.1
      - 3.1.n.n UCn.n
      - 3.1.n.n+1 Requisiti Associati

Riferimenti [http://www.math.uaa.alaska.edu/~afkjm/cs401/IEEE830.pdf](http://www.math.uaa.alaska.edu/~afkjm/cs401/IEEE830.pdf)
